services:
  - type: web
    name: ibm-bank-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python agent.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: BANK_NAME
        value: AI Banking Portal
